---
- name: Add User
  hosts: 192.168.1.73
  tasks:
    - name: Add user
      user:
         name: gizem
         comment: Gizemn11
         group: wheel
         shell: /bin/bash
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: .ssh/id_rsa
         expires: 23231231212
         password: "{{ '1234' | password_hash('sha512') }}"
         update_password: always
      register: gizem   
